# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm439-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter  pinewood pine olives,$(TARGET_DEVICE)),)

endif
